apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  annotations:
     backstage.io/kuberbetes-namespace: A
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
